[package]
name = "dialogs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
gemgui = {path  = "../../gemgui" }

[dependencies]
gemgui = {path  = "../../gemgui" }
bytes = "1.3.0"
home = "0.5.4"

[[bin]]
name = "dialogs"
path = "dialogs.rs"
